idf_component_register(
    SRC_DIRS
        "."
        "audio"
        "kws"
        "protocol"
        "mcp"
        "display"
        "iot"
        "system"
        "notify"
    INCLUDE_DIRS
        "."
        "audio"
        "kws"
        "protocol"
        "mcp"
        "display"
        "iot"
        "system"
        "notify"
    REQUIRES
        driver
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        esp_https_ota
        esp_timer
        nvs_flash
        json
        esp_websocket_client
        esp_tls
        lwip
    EMBED_FILES
        "kws/model_data.tflite"
)
